import os
import sys
import subprocess
from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()

class CockpitOrchestrator:
    """
    Main orchestrator for AgentOps audits.
    Runs Arch Review, Quality Baseline, Red Team, and Performance tests.
    """
    
    def __init__(self):
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.report_path = "cockpit_final_report.md"
        self.results = {}

    def run_step(self, name: str, cmd: list):
        console.print(f"\n🚀 [bold]Step: {name}[/bold]")
        try:
            env = os.environ.copy()
            current_pp = env.get("PYTHONPATH", "")
            env["PYTHONPATH"] = f"src:{current_pp}" if current_pp else "src"
            
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                env=env
            )
            success = result.returncode == 0
            self.results[name] = {
                "success": success,
                "output": result.stdout if success else result.stderr
            }
            if success:
                console.print(f"✅ {name} Completed.")
            else:
                console.print(f"❌ {name} Failed.")
        except Exception as e:
            self.results[name] = {"success": False, "output": str(e)}
            console.print(f"💥 Error running {name}: {e}")

    def generate_report(self):
        report = [
            "# 🏁 AgentOps Cockpit: Final Audit Report",
            f"**Timestamp**: {self.timestamp}",
            f"**Status**: {'PASS' if all(r['success'] for r in self.results.values()) else 'FAIL'}",
            "\n---",
            "\n## 📊 Executive Summary"
        ]
        
        summary_table = Table(show_header=True, header_style="bold magenta")
        summary_table.add_column("Audit Type")
        summary_table.add_column("Status")
        
        for name, data in self.results.items():
            status = "✅ PASS" if data["success"] else "❌ FAIL"
            summary_table.add_row(name, status)
            report.append(f"- **{name}**: {status}")

        console.print("\n", summary_table)
        
        report.append("\n## 🔍 Detailed Findings")
        for name, data in self.results.items():
            report.append(f"\n### {name}")
            report.append("```text")
            report.append(data["output"][-1000:] if data["output"] else "No output.")
            report.append("```")

        report.append("\n---")
        report.append("\n*Generated by the AgentOps Cockpit Orchestrator.*")
        
        with open(self.report_path, "w") as f:
            f.write("\n".join(report))
        
        console.print(f"\n✨ [bold green]Final Report generated at {self.report_path}[/bold green]")

def run_full_audit():
    orchestrator = CockpitOrchestrator()
    
    console.print(Panel.fit(
        "🕹️ [bold blue]AGENTOPS COCKPIT: FULL SYSTEM AUDIT[/bold blue]\nLaunching all governance and optimization modules...",
        border_style="blue"
    ))

    # 1. Architecture Review
    orchestrator.run_step("Architecture Review", [sys.executable, "-m", "backend.ops.arch_review"])
    
    # 2. Quality Baseline
    orchestrator.run_step("Quality Baseline", [sys.executable, "-m", "backend.eval.quality_climber"])
    
    # 3. Security & Secrets
    orchestrator.run_step("Secret Scanner (Leak Detection)", [sys.executable, "-m", "backend.ops.secret_scanner"])
    orchestrator.run_step("Adversarial Security (Red Team)", [sys.executable, "-m", "backend.eval.red_team", "src/backend/agent.py"])
    
    # 4. Face (UI/UX) Audit
    orchestrator.run_step("UI/UX Quality (Face Auditor)", [sys.executable, "-m", "backend.ops.ui_auditor", "src"])
    
    # 5. Token Optimization Audit
    orchestrator.run_step("Token Optimization Audit", [sys.executable, "-m", "backend.optimizer", "src/backend/agent.py", "--no-interactive"])

    # 6. Reliability Audit (Unit + Regression)
    orchestrator.run_step("Reliability (Unit + Regression)", [sys.executable, "-m", "backend.ops.reliability"])

    orchestrator.generate_report()

if __name__ == "__main__":
    run_full_audit()
