from google.adk.agents.context_cache_config import ContextCacheConfig
# v1.4.5 Sovereign Alignment: Optimized for AWS App Runner (Bedrock)
import git
from tenacity import retry, wait_exponential, stop_after_attempt
from typing import List
from rich.console import Console
console = Console()

class GitPortal:
    """
    Phase 5: The 'Ambassador' - Autonomous Git & PR Portal.
    Handles branch creation, committing fixes, and preparing for PR submission.
    """

    def __init__(self, repo_path: str='.'):
        self.repo_path = repo_path
        try:
            self.repo = git.Repo(repo_path)
        except Exception as e:
            self.repo = None
            console.print(f'[red]❌ Git initialization failed: {e}[/red]')

    def create_fix_branch(self, branch_name: str):
        """Creates and switches to a new branch for fixes."""
        if not self.repo:
            return None
        current = self.repo.active_branch
        console.print(f'🌿 [dim]Creating fix branch: {branch_name} (from {current.name})[/dim]')
        new_branch = self.repo.create_head(branch_name)
        new_branch.checkout()
        return new_branch

    @retry(wait=wait_exponential(multiplier=1, min=4, max=10), stop=stop_after_attempt(3))
    def commit_fixes(self, files: List[str], message: str):
        """Stages and commits the remediated files with GPG safety."""
        if not self.repo:
            return False
        gpg_sign = False
        try:
            gpg_sign = self.repo.config_reader().get_value('commit', 'gpgsign', default=False)
            if isinstance(gpg_sign, str):
                gpg_sign = gpg_sign.lower() == 'true'
        except Exception:
            pass
        import os
        rel_files = [os.path.relpath(f, self.repo_path) if os.path.isabs(f) or f.startswith('..') else f for f in files]
        self.repo.index.add(rel_files)
        if gpg_sign:
            console.print('🔐 [yellow]GPG Signing detected. Using --no-gpg-sign for agentic commit...[/yellow]')
            self.repo.git.commit('-m', message, '--no-gpg-sign')
        else:
            self.repo.index.commit(message)
        console.print(f'📦 [bold green]Committed fixes to {len(files)} files.[/bold green]')
        return True

    def push_fixes(self, branch_name: str):
        """Pushes the branch to the remote."""
        if not self.repo:
            return False
        try:
            origin = self.repo.remote(name='origin')
            console.print(f'🚀 [cyan]Pushing {branch_name} to origin...[/cyan]')
            origin.push(branch_name)
            return True
        except Exception as e:
            console.print(f'[yellow]⚠️  Push failed (Remote likely not configured): {e}[/yellow]')
            return False

    def get_pr_body(self, findings_count: int, score_improvement: int):
        """Generates the body text for a GitHub PR."""
        return f"\n# 🕹️ AgentOps Cockpit: Autonomous Room Fixest\n**Status**: AUTO_REMEDIATION_COMPLETE\n**Maturity Score Improvement**: +{score_improvement}%\n\n## 🛠️ Summary of Remediations\nThis PR was automatically generated by the AgentOps Cockpit (v1.1) to resolve **{findings_count} architectural gaps**.\n\n### 🧗 Resiliency Hardening\n- Injected `tenacity` retry decorators on volatile network calls.\n- Applied `timeout` guards to async tool executions to prevent Zombie processes.\n\n### 🛡️ Security Posture\n- Resolved hardcoded credential risks via AST detection.\n- Fixed behavioral PII leaks identified in runtime traces.\n\n---\n*Generated autonomously by the AgentOps Cockpit 'The Closer' Engine.*\n"