import os
import sys
import subprocess
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskID

console = Console()

class CockpitOrchestrator:
    """
    Main orchestrator for AgentOps audits.
    Optimized for concurrency and real-time progress visibility.
    """
    
    def __init__(self):
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.report_path = "cockpit_final_report.md"
        self.results = {}
        self.total_steps = 7
        self.completed_steps = 0

    def run_command(self, name: str, cmd: list, progress: Progress, task_id: TaskID):
        """Helper to run a command and capture output while updating progress."""
        progress.update(task_id, description=f"[cyan]Running {name}...")
        
        env = os.environ.copy()
        current_pp = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = f"src:{current_pp}" if current_pp else "src"
        
        try:
            # We use Popen to potentially stream output if we wanted, 
            # but for now we'll just run it and capture.
            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                env=env
            )
            
            stdout, stderr = process.communicate()
            success = process.returncode == 0
            
            output = stdout if success else f"{stdout}\n{stderr}"
            self.results[name] = {
                "success": success,
                "output": output
            }
            
            if success:
                progress.update(task_id, description=f"[green]✅ {name}", completed=100)
            else:
                progress.update(task_id, description=f"[red]❌ {name} Failed", completed=100)
                
            return name, success
        except Exception as e:
            self.results[name] = {"success": False, "output": str(e)}
            progress.update(task_id, description=f"[red]💥 {name} Error", completed=100)
            return name, False

    PERSONA_MAP = {
        "Architecture Review": "🏛️ Principal Platform Engineer",
        "Policy Enforcement": "⚖️ Governance & Compliance SME",
        "Secret Scanner": "🔐 SecOps Principal",
        "Token Optimization": "💰 FinOps Principal Architect",
        "Reliability (Quick)": "🛡️ QA & Reliability Principal",
        "Quality Hill Climbing": "🧗 AI Quality SME",
        "Red Team Security (Full)": "🚩 Red Team Principal (White-Hat)",
        "Red Team (Fast)": "🚩 Security Architect",
        "Load Test (Baseline)": "🚀 SRE & Performance Principal",
        "Evidence Packing Audit": "📜 Legal & Transparency SME",
        "Face Auditor": "🎭 UX/UI Principal Designer"
    }

    def generate_report(self):
        title = getattr(self, "title", "Audit Report")
        report = [
            f"# 🕹️ AgentOps Cockpit: {title}",
            f"**Timestamp**: {self.timestamp}",
            f"**Status**: {'✅ PASS' if all(r['success'] for r in self.results.values()) else '❌ FAIL'}",
            "\n---",
            "\n## 🧑‍💼 Principal SME Persona Approvals",
            "Each pillar of your agent has been reviewed by a specialized SME persona."
        ]
        
        persona_table = Table(title="🏛️ Persona Approval Matrix", show_header=True, header_style="bold blue")
        persona_table.add_column("SME Persona", style="cyan")
        persona_table.add_column("Audit Module", style="magenta")
        persona_table.add_column("Verdict", style="bold")
        
        for name, data in self.results.items():
            status = "✅ APPROVED" if data["success"] else "❌ REJECTED"
            persona = self.PERSONA_MAP.get(name, "👤 Automated Auditor")
            persona_table.add_row(persona, name, status)
            # Add to markdown report
            report.append(f"- **{persona}** ([{name}]): {status}")

        console.print("\n", persona_table)
        
        report.append("\n## 🔍 System Artifacts & Evidence")
        for name, data in self.results.items():
            report.append(f"\n### {name}")
            report.append("```text")
            # Last 2000 chars for richer detail
            report.append(data["output"][-2000:] if data["output"] else "No output.")
            report.append("```")

        report.append("\n---")
        report.append("\n*Generated by the AgentOps Cockpit Orchestrator (Parallelized Edition).*")
        
        with open(self.report_path, "w") as f:
            f.write("\n".join(report))
        
        console.print(f"\n✨ [bold green]Final Report generated at {self.report_path}[/bold green]")

def run_audit(mode: str = "quick"):
    orchestrator = CockpitOrchestrator()
    
    title = "QUICK SAFE-BUILD" if mode == "quick" else "DEEP SYSTEM AUDIT"
    subtitle = "Essential checks for dev-velocity" if mode == "quick" else "Full benchmarks & stress-testing"
    
    console.print(Panel.fit(
        f"🕹️ [bold blue]AGENTOPS COCKPIT: {title}[/bold blue]\n{subtitle}...",
        border_style="blue"
    ))

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(bar_width=None),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
        console=console,
        expand=True
    ) as progress:
        
        # Detect if we are running from the installed package or from source
        import importlib.util
        if importlib.util.find_spec("agent_ops_cockpit"):
            base_mod = "agent_ops_cockpit"
        else:
            base_mod = "backend"

        # 1. Essential "Safe-Build" Steps (Fast)
        token_opt_cmd = [sys.executable, "-m", f"{base_mod}.optimizer", "src/backend/agent.py", "--no-interactive"]
        if mode == "quick":
            token_opt_cmd.append("--quick")

        steps = [
            ("Architecture Review", [sys.executable, "-m", f"{base_mod}.ops.arch_review"]),
            ("Policy Enforcement", [sys.executable, "-m", f"{base_mod}.ops.policy_engine"]),
            ("Secret Scanner", [sys.executable, "-m", f"{base_mod}.ops.secret_scanner"]),
            ("Token Optimization", token_opt_cmd),
            ("Reliability (Quick)", [sys.executable, "-m", f"{base_mod}.ops.reliability", "--quick"]),
            ("Face Auditor", [sys.executable, "-m", f"{base_mod}.ops.ui_auditor"])
        ]

        # 2. Add "Deep" steps if requested
        if mode == "deep":
            steps.extend([
                ("Quality Hill Climbing", [sys.executable, "-m", f"{base_mod}.eval.quality_climber", "--steps", "10"]),
                ("Red Team Security (Full)", [sys.executable, "-m", f"{base_mod}.eval.red_team", "src/backend/agent.py"]),
                ("Load Test (Baseline)", [sys.executable, "-m", f"{base_mod}.eval.load_test", "run", "--requests", "50", "--concurrency", "5"]),
                ("Evidence Packing Audit", [sys.executable, "-m", f"{base_mod}.ops.arch_review", "--strict"])
            ])
        else:
            # Quick mode still needs a fast security check
            steps.append(("Red Team (Fast)", [sys.executable, "-m", f"{base_mod}.eval.red_team", "src/backend/agent.py"]))
        
        # Add tasks to progress bar
        tasks = {name: progress.add_task(f"[white]Waiting: {name}", total=100) for name, cmd in steps}
        
        # Execute in parallel
        with ThreadPoolExecutor(max_workers=len(steps)) as executor:
            future_to_audit = {
                executor.submit(orchestrator.run_command, name, cmd, progress, tasks[name]): name 
                for name, cmd in steps
            }
            
            for future in as_completed(future_to_audit):
                name, success = future.result()

    orchestrator.title = title
    orchestrator.generate_report()
    
    # Return True if all steps passed
    return all(r["success"] for r in orchestrator.results.values())

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["quick", "deep"], default="quick")
    args = parser.parse_args()
    success = run_audit(mode=args.mode)
    sys.exit(0 if success else 1)
